debug

diff --git a/.github/workflows/config.yml b/.github/workflows/config.yml
--- a/.github/workflows/config.yml
+++ b/.github/workflows/config.yml
@@ -11,6 +11,12 @@ jobs:
         id: response
         run: curl --data-binary @codecov.yml https://codecov.io/validate
 
-      - name: Set Failure Code
-        if: startsWith(steps.response , "Valid!") == false
-        run: exit 1
+      - name: Debug
+        run: echo ${{ steps.response }}
+
+      - name: Debug
+        run: echo ${{ startsWith(steps.response , "Valid!") }}
+
+      # - name: Set Failure Code
+      #   if: startsWith(steps.response , "Valid!")
+      #   run: exit 1
